directories:
  output: release
  buildResources: build
appId: com.xulongzhe.clawbench
productName: ClawBench
executableName: clawbench-desktop
extraResources:
  - from: assets/login.html
    to: login.html
files:
  - filter:
      - dist/
      - package.json
      - '!**/node_modules/.cache'
win:
  target: dir
  icon: build/icon.png
  signAndEditExecutable: false
mac:
  target: dir
  icon: build/icon.icns
linux:
  target: dir
  icon: build/icon.png
electronVersion: 33.4.11
